# Generated by Django 4.2.19 on 2025-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='maroof', max_length=80)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
